[package]
name = "thenexusavenger/pulse"
repository = "https://github.com/TheNexusAvenger/Pulse"
description = "Debug library for Roblox, including simple memory statistics."
license = "MIT"
authors = ["TheNexusAvenger"]
version = "1.1.0"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]